### ISSUE TITLE
[Fizz] Restore `useMemoCache` in renderers with support for Client APIs

### ISSUE THREAD

**Issue by tester-39403** [Test-Organization-394/test1#306]
e.g. in `react-dom/server`: https://codesandbox.io/p/sandbox/usememocache-react-dom-server-nkz4zc?file=%2Fsrc%2Findex.js%3A9%2C1

Broke only recently in https://github.com/facebook/react/pull/31767. No stable release is affected

## Summary

Mainly an oversight since we don't have types based off of feature flags. Now that `enableUseMemoCache` is shipped, `useMemoCache` can be non-nullable.

Discovered during integration testing with Next.js where SSR threw with `TypeError: dispatcher.useMemoCache is not a function` but ultimately recovered due to client-side rendering.

## How did you test this change?

Hardened types.

_Originally a pull request_
